#!/bin/sh

find . -name '*.o' -exec rm -f '{}' ';'
find . -name cheesetracker_qt -exec rm -f '{}' ';'
find . -name moc__* -exec rm -f '{}' ';'
find . -name .sconsign -exec rm -f '{}' ';'
find . -name '*.a' -exec rm -f '{}' ';'
find . -name install.log -exec rm -f '{}' ';'
rm -f detect_cache.py;
rm -f *.pyc;
rm -f cscope.out
rm -f config_errors.log
rm -f test.c a.out test
rm -f core*
rm -f common/stuZBDWW
